#!/bin/sh /etc/rc.common

START=99
STOP=1
process=$(pgrep -f led-wan-trigger)

start(){
    /usr/bin/led-wan-trigger &
}

stop(){
    kill -9 $process
}

restart(){
    kill -9 $process
    /usr/bin/led-wan-trigger &
}

# vim: set ts=4 sts=4 sw=4 et:
