#!/bin/sh /etc/rc.common

START=99
STOP=1
process=$(pgrep -f inet-status)

start(){
    /usr/bin/inet-status &
}

stop(){
    kill -9 $process
}

restart(){
    kill -9 $process
    /usr/bin/inet-status &
}

# vim: set ts=4 sts=4 sw=4 et:
